### ISSUE TITLE
In brapi test data, should pedigree be constructed using germplasmName

### ISSUE THREAD

**Issue by nickmorales** [CIP-RIU/brapiTS#2]
The pedigree is shown as A000001 / A000002, but shouldn't it be Name001/Name002?

**Comment by c5sire** [comment]
Not necessarily; often find a mixture. In genebanks it would be mostly from accessionNumber. Germplasm with the same name may have different sources; each one would have a distinct accession ID. Accession ID must be unique. Probably something to clarify with brapi-team.
